name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache tipi distro files
        uses: actions/cache@v2
        with:
          path: |
            /.tipi/**/_Base/
            /.tipi/gh
            /.tipi/**/gh
            !/.tipi/.*
            !/.tipi/v*
            !/.tipi/downloads
          key: ${{ runner.os }}-build
          restore-keys: |
            ${{ runner.os }}-build
      - name: tipi builds project 
        run: |
          export HOME=/root
          mkdir -p ~/.tipi
          tipi . -t linux --dont-upgrade --verbose --test all 
